---
- name: Create Groups
  group: name={{ user_group }}


- name: Create Users
  user: >
    name={{ item.name }}
    group={{ user_group }}
    groups={{ user_group }}
  with_items:  '{{ users }}'


- name: create user
  user:
    name: "{{ item.name }}"
    createhome: yes
    password: "{{ item.password | password_hash('sha512') }}"
    shell: /usr/bin/zsh
    groups: wheel
    state: present
  with_items:
  - { name: 'adachin', password: 'adachindayo' }
  - { name: 'server', password: 'serverdayo' }
