# ansible-playbook -i <inventory> -l <host> <playbook.yml> --tags <tag_name>
- hosts: all
  become: yes

  tasks:
    - name: install basic rpm
      yum:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - vim-enhanced
        - bash-completion
        - tree
        - git

    - name: install basic rpm
      yum:
        name:
          - git
          - tree


    - name: install httpd
      yum:
        name:
          -httpd
      tags:
        -setup

    - name: install php
      yum:
        name:
          - httpd
          - php
          - php-mysql
        tags:
          - setup

    - name: install Mariadb
      yum:
        name:
          - mariadb
          - mariadb-server
        tags:
          - setup


    - name: start service
      service: name=httpd
               state=started
               enabled=yes

    - name: restart service status
      service: name=httpd
               state=restarted
