# Command modules test
- hosts: all
  tasks:
    - name: hostname
      command: hostname
    - name: ip address
      shell: /usr/sbin/ip a |grep inet
    - name: return memory free
      command: free
    - name: uptime
      command: uptime
